Refurbished gameOver screen
Mafia-Hands/Mafia pull request #130
Opened 2021-03-16 03:16 UTC by Jmcl168

#Uses:
TopBarGame, StatusBar and Player components to display the winning group and winning players (based on mock-up designs)

# Description
This PR fixes #122
I have not added functionality to change text colour yet as it is not in the mock-up.

Added TopBarGame component to gameOver screen.
Added StatusBar component to display winning group. 
Adjusted StatusBar.css to center heading.
Added Players component which shows only players in the winning group.

# Demo

### Copy and paste the following for a successful demo:   

#### Into app.js  
*To test winning player functionality, change groupName in GameOver component to 'Civilian'
```bash
import './App.css';
import PlayScreen from './Pages/PlayScreen';
import Home from './Pages/Home';
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';
import GameOver from './Components/GameOver';

function App() {
    const playerStates = [
        {
            playerId: '1',
            name: 'Player 1',
            state: true,
            role: 'Mafia'
        },
        {
            playerId: '2',
            name: 'Player 2',
            state: false,
            role: 'Civilian'
        },
    ];
    return (
        <Router>
            <Switch>
                <Route exact path="/">
                    <Home />
                </Route>
                <Route path="/play">
                    <PlayScreen />
                </Route>
                <Route path="/gameover">
                    <GameOver
                        players={playerStates}
                        groupName={'Mafia'}
                    />
                </Route>
            </Switch>
        </Router>
    );
}

export default App;
```

#### Into home.js :  
```bash
<li>
       <Link to="/gameover">Game Over</Link>
</li>
<li>
        <Link to="/entry">Entry</Link>
</li>
```
### Preview:  
![game over](https://user-images.githubusercontent.com/61758619/111250059-8d996980-8671-11eb-9e71-408c97d87bb4.PNG)

# Type of change:
* New feature adaptation (Non-breaking change that adds functionality)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

2021-03-16 03:18 UTC, Jmcl168 commented
Navigate to Game Over screen via the link at the top of the home screen

2021-03-18 03:58 UTC, SreenikethRaghavan commented
Can we have some tags, projects and milestones associated with this PR please

2021-03-20 05:52 UTC, Dhors requested changes

2021-03-20 05:52 UTC, Dhors commented on frontend/src/Components/GameOver.jsx
> +                userDetails={['Reeve', 'Civilian']}
Is this supposed to be hardcoded in?

2021-03-20 05:52 UTC, Dhors commented on frontend/src/Components/GameOver.jsx
> +                    {players.map((player, index) => {
Where is index coming from?

2021-03-20 12:26 UTC, closed without merging