Add functionality to Bottom Bar
Mafia-Hands/Mafia pull request #195
Opened 2021-03-19 04:15 UTC by skyn310198

# Description
This PR fixes #113

+Add functionality to the Bottom Bar - be able to track Day/Night of the game
-Exclude chat box - future implementation

# Demo
After:
![image](https://user-images.githubusercontent.com/49630838/111730529-7f985280-88d6-11eb-9a25-e4cdbe8147eb.png)

![image](https://user-images.githubusercontent.com/49630838/111730543-8757f700-88d6-11eb-9c18-b8b3c44412cf.png)

# Type of change:
* New feature (Non-breaking change that adds functionality)

2021-03-19 04:22 UTC, ateagit requested changes
Good stuff

2021-03-19 04:22 UTC, ateagit commented on frontend/src/Components/BottomBar.jsx
>      <div>
Not really a problem but you can access period and number directly here (so you dont have to pass props) by using the context
`const { state } = useContext(GameContext)` (check the StatusBar.js component for an example)

2021-03-19 04:22 UTC, ateagit commented on frontend/src/Socket.js
> +// const socket = new socketIOClient('mafia-hands-backend-cd.herokuapp.com');
Remember to revert this file to use heroku when making a pr

2021-03-19 07:33 UTC, jteo97 approved these changes
Everything looks good to me.

2021-03-19 08:42 UTC, ateagit approved these changes
LGTM

2021-03-19 23:28 UTC, jge385 approved these changes
Good job~ Looks good to me

2021-03-19 23:45 UTC, SiyuQian commented
Good stuff! Thanks.

2021-03-20 00:10 UTC, SiyuQian approved these changes

2021-03-20 08:12 UTC, merged