End game setting
Mafia-Hands/Mafia pull request #199
Opened 2021-03-19 11:28 UTC by skyn310198

# Description
This PR fixes #185

Change the Game Over Setting to be able to open Game Setting

# Demo
After: 
![image](https://user-images.githubusercontent.com/49630838/111773524-2864a300-8913-11eb-8bb1-309f37f877d5.png)

# Type of change:
* Bug fix (Non-breaking change which fixes a bug)

2021-03-19 21:37 UTC, reeved requested changes
Hi Sky, 

Could you please fix the alignment on your header. They aren't centered vertically. 

It might also be worth looking into using the TopBarSettings component since all screens currently use it. Would make styling the app easier in the future. 

But either of these solutions would work :)

2021-03-20 09:46 UTC, reeved requested changes

2021-03-20 09:46 UTC, reeved commented on frontend/src/Pages/GameOverPage.jsx
> +                    <Grid item xs={10} sm={8}><h1>{`WINNER are a ${state.winningRole}`}</h1></Grid>
Could you please make it say "Winner: ${state.winningRole}!!"

2021-03-20 12:26 UTC, Dhors approved these changes
Resolved some quick merge conflicts so we could merge your branch into mafia-hands/mafia 
Otherwise, changes look great!

2021-03-20 12:26 UTC, reeved approved these changes
LGTM

2021-03-20 12:27 UTC, merged