Readme
Mafia-Hands/Mafia pull request #248
Opened 2021-03-24 07:45 UTC by skyn310198

# Description
This PR fixes #244 
Add these into the README
+Contributing
+Author and acknowledgment
+License
+Project status

# Type of change:
* Documentation

2021-03-24 08:37 UTC, reeved requested changes
Looks good, just fix the typo that I mentioned.

2021-03-24 08:37 UTC, reeved commented on README.md
> +If you would like to contribute to this project, please make sure to follow our [Contributing-Guidlines](https://github.com/Mafia-Hands/Mafia/wiki/Contributing-Guidelines)s.
If you would like to contribute to this project, please make sure to follow our [Contributing-Guidelines](https://github.com/Mafia-Hands/Mafia/wiki/Contributing-Guidelines).

2021-03-24 22:30 UTC, jteo97 requested changes

2021-03-24 22:30 UTC, jteo97 commented on README.md
> +
Probably add something some which says we are thanking these two entities below. Right now they are just there under acknowledgement but its weird reading it.

2021-03-25 05:54 UTC, reeved approved these changes
LGTM

2021-03-25 06:42 UTC, jteo97 approved these changes

2021-03-25 06:59 UTC, merged