Close #313 Redesign of the Roles & Rules Screen/Help screen
Mafia-Hands/Mafia pull request #333
Opened 2021-04-14 05:40 UTC by yzho976

# Description
This PR fixes #[313]

Resign both in-lobby and in-game views for the rules and roles page with the new design.

# Demo
![image](https://user-images.githubusercontent.com/55607424/114659614-0e6a8480-9d48-11eb-8fba-53e952687dc6.png)

# Type of change:
(Delete the ones that are not relevant)
* New feature (Non-breaking change that adds functionality)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

2021-04-14 06:02 UTC, JChamberlain28 reviewed
Some concerns but well done

2021-04-14 06:02 UTC, JChamberlain28 commented on backend/events/game-state-events/DayStateChangeEvents.js
> +        const numAlive = room.players.filter((player) => player.status === PlayerStatus.ALIVE).length;
I assume this is an ESLint change

2021-04-14 06:02 UTC, JChamberlain28 commented on frontend/src/Components/RolesAndRules.jsx
>      const roles = [
This is a very good PR, and I am happy to accept, but I am worried that the way the cards are done here promotes code repetition when completing issue #315. If you think that can be avoided, please suggest how.

2021-04-14 06:02 UTC, JChamberlain28 commented on frontend/src/Components/RolesAndRules.jsx
>      const roles = [
I am very worried this significantly increases the complexity of #315 more than needed.

2021-04-14 07:06 UTC, yzho976 commented on backend/events/game-state-events/DayStateChangeEvents.js
> +        const numAlive = room.players.filter((player) => player.status === PlayerStatus.ALIVE).length;
it is

2021-04-14 10:37 UTC, Milk-Yan requested changes
Amazing work Evan!! I've left some information about two changes on Discord, but it's mostly around accounting for different screen sizes :)

2021-04-14 20:39 UTC, AngelaLH reviewed
Implementation matches the design really well, great work! Looks awesome on my big monitor, and should be able to work well on my small screen if scrolling is implemented

2021-04-15 03:20 UTC, khal745 submitted a review, later dismissed
Fantastic work with this, awesome job! Matches the design well! Some minor issues with small screens, but I think its readable and worth adding in. Some small nitpick comments that might be worth changing in the upcoming PRs, but nothing that should stop this getting merged in, in my opinion.

2021-04-15 03:20 UTC, khal745 commented on frontend/src/Components/RolesAndRules.jsx
> +import yourRole from '../images/Your Role.svg'
Nit: Probably better to have file names without spaces in them, but shouldn't be an issue here

2021-04-15 03:20 UTC, khal745 commented on frontend/src/Styles/RolesAndRules.module.css
> +    background-color: #A4B8C4!important;
Nit: This is already defined in the `colorScheme.css` file as cadetBlueCrayola, and you used this in `ModulMUI.module.css`, but easy enough to fix up later.

2021-04-15 03:34 UTC, JChamberlain28 commented on frontend/src/Components/RolesAndRules.jsx
>      const roles = [
It is impractical to change how the code is here given time constraints. #315 is still possible to do, just more complex, so this comment is resolved

2021-04-15 03:36 UTC, JChamberlain28 submitted a review, later dismissed
I have tested this on my computer. I have minor display issues due to my screen resolution and high DPI settings. As this is not evident on a lot of computers, I believe this is acceptable and a bug could be opened if we found this to be an issue in future. Good work, this follows the design accurately and I approve.

2021-04-15 20:35 UTC, Milk-Yan approved these changes
Thank you for the amazing work! I've tested on my local and it's still a bit squished but I'm happy to approve for now and implement the changes later if necessary.

2021-04-15 20:48 UTC, AngelaLH approved these changes
Happy to approve for now as it matches the design closely, great work!

2021-04-16 00:56 UTC, khal745 commented
While the contributor guidelines state that the author should merge their own PR, due to some time zone differences and dependencies on follow up work we merged this PR in on his behalf

2021-04-16 00:56 UTC, merged