Added Player Avatar Overlay to Lobby
Mafia-Hands/Mafia pull request #335
Opened 2021-04-14 23:19 UTC by ODE-BOY

The image of the players roll will be overlayed onto their position on the page.
If a detective respects a mafia the mafia image will be overlayed onto the suspected player.

# Description
This Draft PR is Fixing #317 

This PR will overlay a blank face character avatar over the player's respective character.
It will also overlay the mafia character over the detectives suspect, if said suspect is a mafia.

# Review Clarifications
This issue is not meant to redesign the user avatars, that issue is #305.
These issues are fairly similar and the logic used here will have to be interoperable with #305. At that very least style-wise ie. the size of the images.

I would like a review of my current approach, which will later be completed once issue #305 is complete.

This draft is also to gain a clarification with the character reveal functionality. PR#317 adds functionality to reveal roles to the medic, however, it is the detective with the ability to reveal characters roles not the medic.

# Demo

Before: [Insert Screenshot]
![image](https://user-images.githubusercontent.com/48495086/114791654-f2fc8980-9dda-11eb-9efa-e3fd538d1dbd.png)

After: [Insert Screenshot]
![image](https://user-images.githubusercontent.com/48495086/114791546-d2ccca80-9dda-11eb-9ea9-67be84afc542.png)
![image](https://user-images.githubusercontent.com/48495086/114791734-19222980-9ddb-11eb-9660-0fc353862ef9.png)
![image](https://user-images.githubusercontent.com/48495086/114791711-0c053a80-9ddb-11eb-8349-b7bdc721f5c8.png)

# Type of change:
(Delete the ones that are not relevant)
* New feature (Non-breaking change that adds functionality)

# Checklist:
* Have you merged main into your branch?
* Have you tested your changes to ensure it works as expected and does not break existing functionality?
* If applicable, please ensure sufficient tests are added that is related to the changes.
* Please ensure this PR has a `label`, is linked to an `issue` and is related to a `project`
* If new documentation is required for this change, have you created a new documentation issue that describes the documentation needed?

2021-04-15 10:07 UTC, JChamberlain28 commented
based on the approach taken for #305 you might want to only overlay the hats onto the existing avatars :)

2021-04-16 01:10 UTC, JChamberlain28 requested changes
Please see the closed PR #336 . That does not use overlaying for avatars. This impacts this draft PR. A decision must be made on if this work is to be dropped or continued due to the time constraint. Excellent work so far though.

2021-04-16 11:59 UTC, JChamberlain28 approved these changes
Tested and it works on my pc with 1080p and normal display scaling. Might be worth someone testing on a high DPI screen e.g. a mac or high end windows laptop.

The approach taken is reasonable.
I appreciate the hard work and fast action, bearing in mind this issue was blocked for a bit. 

Good work!

2021-04-16 11:59 UTC, JChamberlain28 commented on frontend/src/Components/Player.jsx
> +
This is a really clean way of doing it. nice!

2021-04-16 22:20 UTC, AngelaLH approved these changes
Looks awesome and matches the design :D There are some instances where it may be appropriate to have the hats showing e.g. on the end screen when the jester won they didn't have their hat, but we can make that a future issue as it wasn't stated in this one.  It's working on my 4K screen but haven't tested on a larger monitor. Thanks for your hard work!
<img width="256" alt="chrome_OKpht9Ynij" src="https://user-images.githubusercontent.com/41172492/115089465-6088f100-9f66-11eb-97b1-92132876d724.png">

2021-04-16 22:30 UTC, AngelaLH reviewed
Just a quick thing - on the role reveal screen only the citizen has a smiley face. Was this the case before your changes? Might want to remove your changes to Medic.svg etc as they are not used in your code, otherwise, all is good :)

2021-04-17 02:03 UTC, JChamberlain28 commented
> Just a quick thing - on the role reveal screen only the citizen has a smiley face. Was this the case before your changes? Might want to remove your changes to Medic.svg etc as they are not used in your code, otherwise, all is good :)

This applies to issue #315

2021-04-19 07:00 UTC, ODE-BOY commented
> 
> 
> > Just a quick thing - on the role reveal screen only the citizen has a smiley face. Was this the case before your changes? Might want to remove your changes to Medic.svg etc as they are not used in your code, otherwise, all is good :)
> 
> This applies to issue #315, the PR for that issue shows a jester with a smiley face so I think this change comes in this PR, #335.



> 
> 
> > Just a quick thing - on the role reveal screen only the citizen has a smiley face. Was this the case before your changes? Might want to remove your changes to Medic.svg etc as they are not used in your code, otherwise, all is good :)
> 
> This applies to issue #315, the PR for that issue shows a jester with a smiley face so I think this change comes in this PR, #335.

Does this mean this is safe to merge?

2021-04-19 09:12 UTC, merged